### ISSUE TITLE
Always get 'Client.Timeout exceeded while awaiting headers' after sent the payment

### ISSUE THREAD

**Issue by rlinxy** [Qitmeer/qitmeer-wallet#76]
We used to send batch payments successfully without problem for several months. Just recently, we always get such error: 
Client.Timeout exceeded while awaiting headers
The payment has already been sent, just seems no correct reply with TXID from the qitmeer-wallet.
I updated to the newest code, but the problem remains the same.
The RPC interface we use is 'wallet_sendToMany', unlock the wallet first, then use this interface to send out batch payment.

**Comment by forchain** [comment]
https://github.com/Qitmeer/qitmeer-wallet/pull/75/files

Is your issue relevant to his commit? Is it reproduced before or after this one?

**Comment by rlinxy** [comment]
I guess it's not related to this commit. We haven't upgrade the for a long time, probably half a year. The wallet has been working fine for several months, just see this happens recently.
So my guess is, maybe it is caused by something new of the blockchain? Or too many transactions and UTXO in the wallet?

**Comment by forchain** [comment]
https://github.com/Qitmeer/qitmeer/issues/423

Probably relates to this bug, investigating. Qitmeer forbids excessive connections from wallet, even crashes

**Comment by rlinxy** [comment]
> [Qitmeer/qitmeer#423](https://github.com/Qitmeer/qitmeer/issues/423)
> 
> Probably relates to this bug, investigating. Qitmeer forbids excessive connections from wallet, even crashes

I don't see there is such error in the log of the node. I just restarted the node, and tried to send payment again, it made no difference, still got such error:
Client.Timeout exceeded while awaiting headers
It's really annoying, plz fix it ASAP, thanks

**Comment by rlinxy** [comment]
Any update? Still waitting :(

**Comment by forchain** [comment]
https://github.com/Qitmeer/qitmeer/issues/423

I was stopped by this issue, I cannot synchronize blocks.

**Comment by forchain** [comment]
@rlinxy I am working around https://github.com/Qitmeer/qitmeer/issues/423 to reproduce your bug

**Comment by forchain** [comment]
@rlinxy we just fixed a synchronization issue, please update qitmeer to see if your issue is gone. And I strongly recommend you make a fresh synchronization.

**Comment by dindinw** [comment]
@rlinxy I think you might consider to provide more detail information for the bug to be useful. detail error log and precise steps to reproduce will help.  `Client.Timeout exceeded while awaiting headers` is just a golang http client connection timeout error. It give only some ambiguous guess for where/what trouble is.

**Comment by dindinw** [comment]
closed by #81

**Comment by rlinxy** [comment]
This bug is still there, and someone from the team is working on it with us. So I guess it's better to make this issue open again.

**Comment by dindinw** [comment]
@rlinxy reopen the issue to trace the process, Please provide more error information here if the #81 not fixed the issue. Please also make sure you had tried the latest code.

**Comment by rlinxy** [comment]
OK, solved, just wait a little bit longer to get response from the wallet. Previously we set the timeout to 30s, and solved by set it to 180s. I guess this issue is due to there are too many UTXOs or transaction history in the wallet of our mining pool.

**Comment by dindinw** [comment]
@rlinxy great, I will close the issue. Please reopen or fire new issue if any future problem.
